[policy]
max_score = 40
min_release_age = "3d"
require_report = true

[registry]
branch = "master"
repo = "ShadowArcanist/safe-cargo"
signing_key = "RWReWDw+dePacXXlacWF07gTUvrGRNvrjDnzKewZFfzVNEk4q4tWiEB/"
